name: Build and Test All Apps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]  # Update the Node.js version if needed

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Backend Setup
      - name: Set up Node.js (Backend)
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./backend/package-lock.json

      - name: Install and Test Backend
        working-directory: ./backend
        run: |
          npm ci
          npm test

      # Frontend Setup
      - name: Set up Node.js (Frontend)
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./frontend/package-lock.json

      - name: Install and Test Frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm test

      # Admin Setup
      - name: Set up Node.js (Admin)
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./admin/package-lock.json

      - name: Install and Test Admin
        working-directory: ./admin
        run: |
          npm ci
          npm test