name: Build and Test All Apps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3  # Ensure this step is BEFORE setup-node

      # Step 2: Set up Node.js and Cache Dependencies for Backend
      - name: Set up Node.js (Backend)
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './backend/package-lock.json'

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: |
          npm install
          npm run server &

      # Step 3: Set up Node.js and Cache Dependencies for Frontend
      - name: Set up Node.js (Frontend)
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: |
          npm install
          npm run dev &

      # Step 4: Set up Node.js and Cache Dependencies for Admin
      - name: Set up Node.js (Admin)
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './admin/package-lock.json'

      - name: Install Admin Dependencies
        working-directory: ./admin
        run: |
          npm install
          npm run dev &
