name: Build and Test All Apps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]  # Adjust if you're using a different version of Node.js

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Install and Test Backend
      - name: Install and Test Backend
        working-directory: ./backend
        run: |
          npm install
          npm run server &  # Run the backend server
          npm test           # Run backend tests if you have them

      # Step 4: Install and Test Frontend
      - name: Install and Test Frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run dev &      # Run the frontend
          npm test           # Run frontend tests if you have them

      # Step 5: Install and Test Admin
      - name: Install and Test Admin
        working-directory: ./admin
        run: |
          npm install
          npm run dev &      # Run the admin panel
          npm test           # Run admin tests if you have them
