name: Build and Test All Apps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Install Backend Dependencies
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: |
          npm ci   # Faster installation using lock file
          npm run server &  # Optional if server needs to run during testing

      # Step 4: Install Frontend Dependencies
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: |
          npm ci
          npm run dev &  # Optional if frontend needs to run during testing

      # Step 5: Install Admin Dependencies
      - name: Install Admin Dependencies
        working-directory: ./admin
        run: |
          npm ci
          npm run dev &  # Optional if admin panel needs to run during testing
