name: Build and Test All Apps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]  # Adjust if you're using a different version of Node.js

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Install Dependencies for Backend
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: |
          npm install
          npm run server &  # Start the backend server (optional)

      # Step 4: Install Dependencies for Frontend
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: |
          npm install
          npm run dev &  # Start the frontend (optional)

      # Step 5: Install Dependencies for Admin
      - name: Install Admin Dependencies
        working-directory: ./admin
        run: |
          npm install
          npm run dev &  # Start the admin panel (optional)
